### PR TITLE
Validation for Run Page Form Fields + Convert FormData to RequestBody

### LINKED ISSUE #199: [Frontend] Add validation for Run page
AC: The form used for the model run page should include basic validation. The Run Task button should produce red error message under the associated input field if the value has not been chosen. See: https://github.com/UMass-Rescue/RescueBox-Desktop/blob/main/src/renderer/model-apps/isr-model/ISRModelRun.tsx for example, although we don't know the number/types of input fields at compile time.

### LINKED ISSUE #200: [Frontend] Add logic to form Request Body
AC: Write some kind of utility class/module/function to take FormData and convert it into a RequestBody

### PR DESCRIPTION
**Pull request by ShriramG24**
Closes #199 
Closes #200 

image

image

### CODE REVIEW

**Comment by Shreneken** [comment]
It might be a good idea to add type validation for strings in numeric fields since we know the input data type. Otherwise, it looks pretty good.

**Comment by atharvakale343** [comment]
`IntField` doesn't validate for integer right?

**Review by atharvakale343 — DISMISSED** [review]
LGTM, need validation for `IntField`

**Comment by ShriramG24** [comment]
> It might be a good idea to add type validation for strings in numeric fields since we know the input data type. Otherwise, it looks pretty good.

The numeric fields don't allow you to enter text, so we should be good I think.

**Comment by Shreneken** [comment]
Validation for int | float in corresponding input fields?

**Comment by ShriramG24** [comment]
> Validation for int | float in corresponding input fields?

I'm not allowing user to enter float in `IntField`. If they try to add a decimal place then it automatically floors it. Is that fine? Basically this ensures that the backend won't receive a float when it needs to get an int.

As for integer in `FloatField`, I think that's fine and should be allowed.

**Comment by atharvakale343** [comment]
Can we use one of these? https://stackoverflow.com/a/8808608

**Review by atharvakale343 — APPROVED** [review]
LGTM

**Pull request merged**
