### PR TITLE
reduced Jobs page to a single table for both running and finished jobs

### LINKED ISSUE #217: [Frontend] Reduce Jobs page to Single Table
AC: Jobs page should have a single table arranged in descending order of start time where running jobs appear at its head. When a job completes, only that row should change in-place, preventing a large, disorienting layout shift.

### PR DESCRIPTION
**Pull request by Shreneken**
Closes #217 

image

### CODE REVIEW

**Comment by Shreneken** [comment]
Fixed bug related to `endtime`. 
See new attached ss:

image

Ideas for replacing 'Running' in the `endtime` column for running jobs?

**Comment by atharvakale343** [comment]
we can leave it blank?

**Review by atharvakale343 — APPROVED** [review]
LGTM

**Comment by Shreneken** [comment]
Here's the updated ss:
image

**Pull request merged**
