### PR TITLE
Quick select

### LINKED ISSUE #256: [Frontend] Add quick select button for Registration
AC: When registering a model IP (in the modal), add a button under the input boxes for IP address and port with the label “127.0.0.1” and “5000” respectively. When a user clicks these buttons, the input boxes are filled in with the associated value

### PR DESCRIPTION
**Pull request by atharvakale343**
image

Closes #256

### CODE REVIEW

**Review by ShriramG24 — COMMENTED** [review]
It would be nice if the connect button was aligned with the input fields. Is this something we will be including in release or is it just for our convenience?

**Comment by atharvakale343** [comment]
Yes included in the release. Maybe you could have more than one button? Putting it directly  under looks pretty confusing because you’re greeted with a text box and a random button under it, and you don’t know for sure what that button does.

**Comment by ShriramG24** [comment]
Yeah, that and I feel like it won't be too useful for the port. For the server address, it's convenient because usually the servers will be running locally. But only one server can run on port 5000. For any other server, the user will have to enter the value anyways. We can include multiple options but need to find a way to do that without crowding the modal.

**Comment by atharvakale343** [comment]
Is this fine for now? 127.0.0.1 and 5000 are probably going to be the most used for now.

**Review by ShriramG24 — APPROVED** [review]

**Pull request merged**
