### PR TITLE
Revamped Job Details page

### PR DESCRIPTION
**Pull request by Shreneken**
Completed:
- Changed Job Details page styling to be a 2 Column grid
   - First column shows Job Metadata: Status, Status Text and Rety Button (If failed) Start Time, End Time
   - Second column shows Task Metadata: Model, Task route, Task Inputs, Task Parameters and a button for modal display of raw JSON request body

Problems: I couldn't find a way to link a job to a task directly (with only having "taskRoute" within job data), need this for several reasons:
- To display Task's short title as what task was conducted
- Clickable link that will go to specific tab for the task
- To parse the request body for inputs/parameters of correct type

Screenshots of current iteration:

image
image
image

### CODE REVIEW

**Comment by atharvakale343** [comment]
I like the elements a lot. I don’t really like the grid, lot of unused space below End Time (especially if the task inputs/parameters are pretty long), and the right side elements could use the horizontal space. Maybe you want to use a column?

**Comment by Shreneken** [comment]
Updated the design and implemented the following:
- "Disabled" functionality on InputField and ParameterField elements and that is inherited (and implemented) in all of their children elements

Additional notes:
- The Jobs page currently allows running jobs be clicked for details, which results in a error - will fix this when reworking jobs page.

Updated screenshots:
image

**Comment by Shreneken** [comment]
Closes #202

**Review by atharvakale343 — APPROVED** [review]
Noiceu

**Pull request merged**
