### PR TITLE
Refactor BatchFileResponse to Support List/Grid View

### LINKED ISSUE #290: Refactor BatchFileResponse Component to Use Tanstack React Table
AC: The current BatchFileResponse Component doesn't really match what we have going on with the other batch response components. Use the same datatable to render the expandable dropdowns.

Look at `BatchDirectoryView.tsx` for an example.

### PR DESCRIPTION
**Pull request by ShriramG24**
Closes #290 

Some sus stuff going on in `Datatable.tsx` since it's overloaded (supporting text table, directory table, and file table). I can split it into three different tables, but there would be a lot of code duplication. It's mostly fine except the file preview is hard to integrate into the existing setup. Let me know what you guys think.

Grid/List View:

https://github.com/user-attachments/assets/b7c51feb-4d1f-441f-86d8-dfe4036b2806

Pagination:

https://github.com/user-attachments/assets/295f23b7-387f-48d5-b5a1-0db94a0e6661

### CODE REVIEW

**Comment by atharvakale343** [comment]
I think there's a lot of good thoughts here. Can you elaborate on your findings/experience when trying to add pagination? How is the grid created currently?

**Comment by ShriramG24** [comment]
> Can you elaborate on your findings/experience when trying to add pagination? How is the grid created currently?

I didn't try extensively but thought we can save it for another issue/PR. Obviously it should be possible to add it to the grid (maybe [this package](https://www.npmjs.com/package/react-paginate) could work?), but it's not free like with the table, which is fine. The grid isn't any different from what we had before btw; no extra dependencies. I just reformatted the card to look better.

**Comment by ShriramG24** [comment]
You can ignore my above comment. Turns out I was just being lazy. The PR should be ready to review now.

**Comment by atharvakale343** [comment]
Nice! Can you use fixed height for the collapsible div so the buttons don't move?

**Comment by ShriramG24** [comment]
> Nice! Can you use fixed height for the collapsible div so the buttons don't move?

Done

**Review by atharvakale343 — APPROVED** [review]
Nice! Looks OP.

**Pull request merged**
