### PR TITLE
Able to view input/output directory in file explorer from job details page

### PR DESCRIPTION
**Pull request by ShriramG24**

### CODE REVIEW

**Comment by ShriramG24** [comment]
Error dialog:
image

**Comment by atharvakale343** [comment]
> Error dialog: image

Nice!

image

**Comment by ShriramG24** [comment]
> There's also this. Can we use it?

Yeah, I tried that initially, but the thing is that if `shell.openPath` executes on an invalid path, an error dialog is fired by the file explorer before we get to handle the error, like shown below (atleast on Windows). If we want a custom error dialog in the future then this isn't ideal.

image

**Comment by atharvakale343** [comment]
> > There's also this. Can we use it?
> 
> Yeah, I tried that initially, but the thing is that if `shell.openPath` executes on an invalid path, an error dialog is fired by the file explorer before we get to handle the error, like shown below (atleast on Windows). If we want a custom error dialog in the future then this isn't ideal.
> 
> image

I see. MacOS doesn't throw an error at all. I think this is good.

**Review by atharvakale343 — APPROVED** [review]
LGTM

**Pull request merged**
