### PR TITLE
Add notifications for job completion/failure

### LINKED ISSUE #218: [Combined] Notification on Job Complete
AC: When a job completes, a system notification is dispatched. On clicking the notification, this takes you to the Job details page of that job. This will required main->renderer communication, a new paradigm that’s not in this project yet. Notification can easily be dispatched by just the backend, but when a user clicks the notification, a message will have to be dispatched from main->renderer to move to the appropriate page.

### PR DESCRIPTION
**Pull request by ShriramG24**
Closes #218 

Works on Windows. Should check on MacOS and Linux to see if anything additional needs to be done.

Screenshot 2024-11-06 221247

### CODE REVIEW

**Comment by atharvakale343** [comment]
I tried fixing this yesterday. It seems like `window.xxxx` properties haven’t had a chance to be injected yet. You can console.log `window` within the NavigationListener component and see this.

**Comment by ShriramG24** [comment]
> I tried fixing this yesterday. It seems like `window.xxxx` properties haven’t had a chance to be injected yet. You can console.log `window` within the NavigationListener component and see this.

Yeah. Check out the most recent commit, is that fine? I think it's a Jest issue.

**Comment by atharvakale343** [comment]
A log would be nice when it’s undefined

**Review by Shreneken — APPROVED** [review]
LGTM

**Pull request merged**
